/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  FbpNode,
} from './types/node';

export namespace Components {
  interface FbpConnection {}
  interface FbpMain {
    'nodes': FbpNode[];
  }
  interface FbpNode {
    'activate': (state: boolean) => Promise<void>;
  }
  interface FbpXyz {}
}

declare global {


  interface HTMLFbpConnectionElement extends Components.FbpConnection, HTMLStencilElement {}
  var HTMLFbpConnectionElement: {
    prototype: HTMLFbpConnectionElement;
    new (): HTMLFbpConnectionElement;
  };

  interface HTMLFbpMainElement extends Components.FbpMain, HTMLStencilElement {}
  var HTMLFbpMainElement: {
    prototype: HTMLFbpMainElement;
    new (): HTMLFbpMainElement;
  };

  interface HTMLFbpNodeElement extends Components.FbpNode, HTMLStencilElement {}
  var HTMLFbpNodeElement: {
    prototype: HTMLFbpNodeElement;
    new (): HTMLFbpNodeElement;
  };

  interface HTMLFbpXyzElement extends Components.FbpXyz, HTMLStencilElement {}
  var HTMLFbpXyzElement: {
    prototype: HTMLFbpXyzElement;
    new (): HTMLFbpXyzElement;
  };
  interface HTMLElementTagNameMap {
    'fbp-connection': HTMLFbpConnectionElement;
    'fbp-main': HTMLFbpMainElement;
    'fbp-node': HTMLFbpNodeElement;
    'fbp-xyz': HTMLFbpXyzElement;
  }
}

declare namespace LocalJSX {
  interface FbpConnection {}
  interface FbpMain {
    'nodes'?: FbpNode[];
  }
  interface FbpNode {}
  interface FbpXyz {}

  interface IntrinsicElements {
    'fbp-connection': FbpConnection;
    'fbp-main': FbpMain;
    'fbp-node': FbpNode;
    'fbp-xyz': FbpXyz;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'fbp-connection': LocalJSX.FbpConnection & JSXBase.HTMLAttributes<HTMLFbpConnectionElement>;
      'fbp-main': LocalJSX.FbpMain & JSXBase.HTMLAttributes<HTMLFbpMainElement>;
      'fbp-node': LocalJSX.FbpNode & JSXBase.HTMLAttributes<HTMLFbpNodeElement>;
      'fbp-xyz': LocalJSX.FbpXyz & JSXBase.HTMLAttributes<HTMLFbpXyzElement>;
    }
  }
}


